import Phaser from 'phaser';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreloadScene' });
  }

  preload() {
    const width = this.cameras.main.width;
    const height = this.cameras.main.height;

    // Background
    this.cameras.main.setBackgroundColor('#121224');

    // Loading title
    this.add.text(width / 2, height / 2 - 80, 'CARGANDO RECURSOS', {
      font: '700 24px Inter, monospace',
      color: '#00ff88'
    }).setOrigin(0.5);

    // Progress bar box
    const progressBox = this.add.graphics();
    progressBox.fillStyle(0x1e1e3c, 0.8);
    progressBox.fillRoundedRect(width / 2 - 160, height / 2 - 20, 320, 40, 12);

    const progressBar = this.add.graphics();
    const percentText = this.add.text(width / 2, height / 2, '0%', {
      font: '600 16px Inter, monospace',
      color: '#ffffff'
    }).setOrigin(0.5);

    this.load.on('progress', (value: number) => {
      progressBar.clear();
      progressBar.fillStyle(0x00ff88, 1);
      progressBar.fillRoundedRect(width / 2 - 156, height / 2 - 16, 312 * value, 32, 10);
      percentText.setText(Math.round(value * 100) + '%');
    });

    this.load.on('complete', () => {
      progressBar.destroy();
      progressBox.destroy();
      percentText.destroy();
    });

    // Load real image assets generated by AI
    this.load.video('menu_char_video', '/assets/menu_char.mp4');
    this.load.video('menu_inicial_video', '/assets/menu_inicial.mp4');
    this.load.image('bg_stadium', '/assets/bg_stadium.png');
    this.load.image('bg_stadium_fire', '/assets/bg_stadium_fire.png');
    this.load.image('bg_stadium_future', '/assets/bg_stadium_future.png');
    this.load.image('bg_bombonera', '/assets/bg_bombonera.png');
    this.load.video('video_bombonera', '/assets/bombonera.webm');
    this.load.audio('ambiental', '/assets/ambiental.mp3');
    this.load.audio('gool', '/assets/gool.mp3');
    this.load.audio('hover', '/assets/hover.mp3');
    this.load.audio('music', '/assets/music.mp3');
    this.load.image('char_messi', '/assets/char_messi.png');
    this.load.image('char_cristianoR', '/assets/char_cristianoR.png');
    this.load.image('char_neymar', '/assets/char_neymar.png');
    this.load.image('char_mbappe', '/assets/char_mbappe.png');
    this.load.image('char_haaland', '/assets/char_haaland.png');
    this.load.image('char_modric', '/assets/char_modric.png');
    this.load.image('char_messi_2009', '/assets/char_messi_2009.png');
    this.load.image('char_messi_2010', '/assets/char_messi_2010.png');
    this.load.image('char_cristianoR_2008', '/assets/char_cristianoR_2008.png');
    this.load.image('char_neymar_2011', '/assets/char_neymar_2011.png');
    this.load.image('char_ronaldinho', '/assets/char_ronaldinho.png');
    this.load.image('char_paolo_gerrero', '/assets/char_paolo_gerrero.png');
    this.load.image('char_pele', '/assets/char_pele.png');
    this.load.image('char_maradona', '/assets/char_maradona.png');
    this.load.image('char_vinicius', '/assets/char_vinicius.png');
    this.load.image('char_vidal', '/assets/char_vidal.png');
    this.load.image('char_ronaldo', '/assets/char_ronaldo.png');
    this.load.image('char_alexis', '/assets/char_alexis.png');
    this.load.image('char_lamine_yamal', '/assets/char_lamine_yamal.png');
    this.load.image('char_benzema', '/assets/char_benzema.png');
    this.load.image('goal', '/assets/goal.png');
    this.load.image('ball', '/assets/ball.png');
    this.load.image('ball_fire', '/assets/ball_fire.png');
    this.load.image('ball_retro', '/assets/ball_retro.png');
    // Partícula para estelas y UI (re-usamos el procedural solo para esto)
    this.createPlaceholderTextures();
  }

  create() {
    // Go to AuthScene right after preloading
    this.scene.start('AuthScene');
  }

  private createPlaceholderTextures() {
    // Particle texture (small glowing circle)
    const g = this.make.graphics({ x: 0, y: 0 });
    g.fillStyle(0x00ff88, 1);
    g.fillCircle(4, 4, 4);
    g.generateTexture('particle', 8, 8);
    g.destroy();
  }
}
